name: jendral_muda_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  lottie: ^3.1.2
  mat_month_picker_dialog: ^1.1.2
  open_file: ^3.2.1
  path: ^1.9.0
  path_provider: ^2.0.7
  photo_view: ^0.15.0
  string_extensions: ^0.7.1
  transitioned_indexed_stack: ^1.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
